# Configuración de PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alex
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
